# Generated by Django 6.0.3 on 2026-03-30 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(verbose_name='Sayim Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandi'), ('approved', 'Onaylandi')], default='pending', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.project', verbose_name='Proje')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Stok Sayim',
                'verbose_name_plural': 'Stok Sayimlari',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sistem Miktari')),
                ('counted_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sayilan Miktar')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockcount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Urun')),
            ],
            options={
                'verbose_name': 'Sayim Kalemi',
                'verbose_name_plural': 'Sayim Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='StockSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_no', models.CharField(max_length=50, unique=True, verbose_name='Fis No')),
                ('slip_type', models.CharField(choices=[('entry', 'Giris Fisi'), ('exit', 'Cikis Fisi'), ('transfer', 'Transfer Fisi'), ('count', 'Sayim Fisi'), ('delivery', 'Teslim Fisi')], max_length=20, verbose_name='Fis Turu')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('confirmed', 'Onaylandi'), ('cancelled', 'Iptal Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_slips', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slips', to=settings.AUTH_USER_MODEL, verbose_name='Olusturan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='parameters.project', verbose_name='Proje')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_slips', to=settings.AUTH_USER_MODEL, verbose_name='Stok Personeli')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_slips', to='parameters.project', verbose_name='Hedef Proje')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_slips', to='parameters.warehouse', verbose_name='Hedef Depo')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Stok Fisi',
                'verbose_name_plural': 'Stok Fisleri',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Giris'), ('out', 'Cikis'), ('transfer_out', 'Transfer Cikis'), ('transfer_in', 'Transfer Giris'), ('count_adj', 'Sayim Duzeltme')], max_length=20, verbose_name='Hareket Turu')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miktar')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('date', models.DateTimeField(verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Islem Yapan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Urun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.project', verbose_name='Proje')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.warehouse', verbose_name='Depo')),
                ('slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock.stockslip', verbose_name='Fis')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='stockcount',
            name='slip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='count_record', to='stock.stockslip', verbose_name='Fis'),
        ),
        migrations.CreateModel(
            name='StockSlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Birim Fiyat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Urun')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockslip', verbose_name='Fis')),
            ],
            options={
                'verbose_name': 'Fis Kalemi',
                'verbose_name_plural': 'Fis Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='ProjectStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Miktar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.location', verbose_name='Lokasyon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stocks', to='products.product', verbose_name='Urun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='parameters.project', verbose_name='Proje')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.room', verbose_name='Oda')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Proje Stok',
                'verbose_name_plural': 'Proje Stoklari',
                'unique_together': {('product', 'project', 'warehouse', 'location', 'room')},
            },
        ),
    ]
