# Generated by Django 6.0.3 on 2026-03-30 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Barkod')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Demirbas Kodu')),
                ('name', models.CharField(max_length=500, verbose_name='Ad')),
                ('serial_no', models.CharField(blank=True, max_length=200, verbose_name='Seri No')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Model')),
                ('unit', models.CharField(default='adet', max_length=20, verbose_name='Birim')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Miktar')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('maintenance', 'Bakimda'), ('retired', 'Kullanim Disi'), ('lost', 'Kayip')], default='active', max_length=20, verbose_name='Durum')),
                ('warranty_start', models.DateField(blank=True, null=True, verbose_name='Garanti Baslangic')),
                ('warranty_years', models.IntegerField(default=0, verbose_name='Garanti Suresi (Yil)')),
                ('maintenance_period_months', models.IntegerField(default=0, verbose_name='Bakim Periyodu (Ay)')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Son Bakim Tarihi')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Sonraki Bakim Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zimmetli Kisi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Olusturan')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.location', verbose_name='Lokasyon')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maincategory', verbose_name='Ana Kategori')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.project', verbose_name='Proje')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory', verbose_name='Alt Kategori')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Demirbas',
                'verbose_name_plural': 'Demirbaslar',
                'ordering': ['name'],
            },
        ),
    ]
