# Generated by Django 6.0.3 on 2026-03-30 10:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Yonetici'), ('manager', 'Mudur'), ('staff', 'Personel'), ('warehouse', 'Depocu')], default='staff', max_length=20, verbose_name='Rol')),
                ('tc_kimlik', models.CharField(blank=True, max_length=11, verbose_name='TC Kimlik No')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Cep Telefonu')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='Is Telefonu')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Firma Adi')),
                ('authorized_name', models.CharField(blank=True, max_length=100, verbose_name='Yetkili Adi')),
                ('authorized_surname', models.CharField(blank=True, max_length=100, verbose_name='Yetkili Soyadi')),
                ('country', models.CharField(default='Turkiye', max_length=100, verbose_name='Ulke')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Il')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Ilce')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Unvan/Gorevi')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylandi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('projects', models.ManyToManyField(blank=True, to='parameters.project', verbose_name='Atanan Projeler')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanici',
                'verbose_name_plural': 'Kullanicilar',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
