# Generated by Django 6.0.3 on 2026-03-30 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('parameters', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('tc_kimlik', models.CharField(blank=True, max_length=11, verbose_name='TC Kimlik')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Unvan/Gorevi')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Miktar')),
                ('assignment_date', models.DateField(verbose_name='Zimmet Tarihi')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Iade Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('returned', 'Iade Edildi'), ('lost', 'Kayip'), ('damaged', 'Hasarli')], default='active', max_length=20, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Demirbas')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Olusturan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Malzeme')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Zimmet',
                'verbose_name_plural': 'Zimmetler',
                'ordering': ['-assignment_date'],
            },
        ),
    ]
