# Generated by Django 6.0.3 on 2026-03-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_entry_counter', models.IntegerField(default=1, verbose_name='Stok Giris Fisi Sayaci')),
                ('stock_exit_counter', models.IntegerField(default=1, verbose_name='Stok Cikis Fisi Sayaci')),
                ('delivery_counter', models.IntegerField(default=1, verbose_name='Teslim Fisi Sayaci')),
                ('transfer_counter', models.IntegerField(default=1, verbose_name='Transfer Fisi Sayaci')),
                ('count_counter', models.IntegerField(default=1, verbose_name='Stok Sayim Fisi Sayaci')),
            ],
            options={
                'verbose_name': 'Genel Ayar',
                'verbose_name_plural': 'Genel Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Lokasyon (Kat)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Lokasyon',
                'verbose_name_plural': 'Lokasyonlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Proje Adi')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Proje Kodu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Oda/Alan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='parameters.location', verbose_name='Lokasyon')),
            ],
            options={
                'verbose_name': 'Oda/Alan',
                'verbose_name_plural': 'Odalar/Alanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Depo/Bina Adi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='parameters.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Depo/Bina',
                'verbose_name_plural': 'Depolar/Binalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='parameters.warehouse', verbose_name='Depo/Bina'),
        ),
    ]
