# Generated by Django 6.0.3 on 2026-03-30 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='Siparis No')),
                ('order_type', models.CharField(choices=[('standard', 'Standart'), ('urgent', 'Acil'), ('planned', 'Planli')], default='standard', max_length=20, verbose_name='Siparis Turu')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandi'), ('preparing', 'Hazirlaniyor'), ('shipped', 'Gonderildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'Iptal')], default='pending', max_length=20, verbose_name='Durum')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Siparis Tarihi')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Saat')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='parameters.project', verbose_name='Proje')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_orders', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.warehouse', verbose_name='Talep Eden Depo')),
            ],
            options={
                'verbose_name': 'Siparis',
                'verbose_name_plural': 'Siparisler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Siparis Miktari')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Teslim Edilen')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Birim Fiyat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Siparis')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Urun')),
            ],
            options={
                'verbose_name': 'Siparis Kalemi',
                'verbose_name_plural': 'Siparis Kalemleri',
            },
        ),
    ]
