# Generated by Django 6.0.3 on 2026-03-30 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ana Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ana Kategori',
                'verbose_name_plural': 'Ana Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Alt Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.maincategory', verbose_name='Ana Kategori')),
            ],
            options={
                'verbose_name': 'Alt Kategori',
                'verbose_name_plural': 'Alt Kategoriler',
                'ordering': ['name'],
                'unique_together': {('main_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Barkod')),
                ('stock_code', models.CharField(blank=True, max_length=100, verbose_name='Stok Kodu')),
                ('name', models.CharField(max_length=500, verbose_name='Urun Adi')),
                ('unit', models.CharField(choices=[('adet', 'Adet'), ('kg', 'Kilogram'), ('lt', 'Litre'), ('mt', 'Metre'), ('m2', 'Metrekare'), ('paket', 'Paket'), ('kutu', 'Kutu'), ('takim', 'Takim'), ('cift', 'Cift'), ('top', 'Top')], default='adet', max_length=20, verbose_name='Birim')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fiyat')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Model')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('critical_stock_level', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='Kritik Stok Seviyesi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Urun Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Olusturan')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maincategory', verbose_name='Ana Kategori')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory', verbose_name='Alt Kategori')),
            ],
            options={
                'verbose_name': 'Urun',
                'verbose_name_plural': 'Urunler',
                'ordering': ['name'],
            },
        ),
    ]
